-- Michelin City Coverage & Expansion: city-only prerequisite for the 632
-- LOCATION_PENDING Belgium+France restaurant backlog (see
-- supabase/data/enrichment/michelin_city_coverage/CITY_COVERAGE_REPORT.md).
--
-- Adds ONLY public.cities rows -- no restaurants, no award_history, no
-- other table touched. Source: missing_cities.csv (397 rows: 73 BE + 324
-- FR), itself audited against a live production cities snapshot
-- immediately before this migration was written (26 BE+FR rows, 0 drift).
--
-- Idempotent by construction: ON CONFLICT targets cities_unique_key
-- (country_code, name, coalesce(region, '')), the table's real unique
-- index -- safe to re-run/re-push without creating duplicates.
--
-- id: database-generated via cities.id's own default gen_random_uuid().
-- postal_municipality / michelin_guide_edition: left NULL, matching every
-- pre-existing BE/FR cities row today.
-- region: populated ONLY for the 4 rows independently verified this pass
-- (Montreuil, Saint-Germain, Saint-Remy, Saint-Medard -- see
-- CITY_COVERAGE_REPORT.md 'homonym-risk checks') -- every other row
-- matches the existing convention of region = NULL.

insert into public.cities (country_code, name, region)
values
  ('BE', 'Aalst', NULL),
  ('BE', 'Arlon', NULL),
  ('BE', 'Bazel', NULL),
  ('BE', 'Beuzet', NULL),
  ('BE', 'Blaregnies', NULL),
  ('BE', 'Borgerhout', NULL),
  ('BE', 'Bouge', NULL),
  ('BE', 'Braine-l''Alleud', NULL),
  ('BE', 'Braine-le-Château', NULL),
  ('BE', 'Damme', NULL),
  ('BE', 'Dave', NULL),
  ('BE', 'De Panne', NULL),
  ('BE', 'Dilsen-Stokkem', NULL),
  ('BE', 'Durbuy', NULL),
  ('BE', 'Eghezée', NULL),
  ('BE', 'Elverdinge', NULL),
  ('BE', 'Emptinne', NULL),
  ('BE', 'Flobecq', NULL),
  ('BE', 'Francorchamps', NULL),
  ('BE', 'Geel', NULL),
  ('BE', 'Genk', NULL),
  ('BE', 'Gentbrugge', NULL),
  ('BE', 'Grandhan', NULL),
  ('BE', 'Hasselt', NULL),
  ('BE', 'Heverlee', NULL),
  ('BE', 'Hulshout', NULL),
  ('BE', 'Ixelles', NULL),
  ('BE', 'Jodoigne', NULL),
  ('BE', 'Koewacht', NULL),
  ('BE', 'Kontich', NULL),
  ('BE', 'Kortrijk', NULL),
  ('BE', 'Leefdaal', NULL),
  ('BE', 'Lichtaart', NULL),
  ('BE', 'Lier', NULL),
  ('BE', 'Liège', NULL),
  ('BE', 'Lotenhulle', NULL),
  ('BE', 'Marche-en-Famenne', NULL),
  ('BE', 'Marchin', NULL),
  ('BE', 'Marenne', NULL),
  ('BE', 'Marke', NULL),
  ('BE', 'Mechelen', NULL),
  ('BE', 'Namur', NULL),
  ('BE', 'Nieuwkerken-Waas', NULL),
  ('BE', 'Ohain', NULL),
  ('BE', 'Oostende', NULL),
  ('BE', 'Ordingen', NULL),
  ('BE', 'Oudenburg', NULL),
  ('BE', 'Ouwegem', NULL),
  ('BE', 'Paliseul', NULL),
  ('BE', 'Quévy-le-Grand', NULL),
  ('BE', 'Roucourt', NULL),
  ('BE', 'Saint-Vith', NULL),
  ('BE', 'Seneffe', NULL),
  ('BE', 'Sint-Denijs', NULL),
  ('BE', 'Sint-Denijs-Westrem', NULL),
  ('BE', 'Sint-Idesbald', NULL),
  ('BE', 'Sint-Katelijne-Waver', NULL),
  ('BE', 'Sint-Kruis', NULL),
  ('BE', 'Sint-Martens-Bodegem', NULL),
  ('BE', 'Sint-Martens-Voeren', NULL),
  ('BE', 'Soheit-Tinlot', NULL),
  ('BE', 'Temploux', NULL),
  ('BE', 'Tienen', NULL),
  ('BE', 'Tongeren', NULL),
  ('BE', 'Turnhout', NULL),
  ('BE', 'Villers-sur-Lesse', NULL),
  ('BE', 'Waasmunster', NULL),
  ('BE', 'Woluwe-Saint-Lambert', NULL),
  ('BE', 'Wommelgem', NULL),
  ('BE', 'Wéris', NULL),
  ('BE', 'Zedelgem', NULL),
  ('BE', 'Zele', NULL),
  ('BE', 'Zonhoven', NULL),
  ('FR', 'Ainhoa', NULL),
  ('FR', 'Aix-en-Provence', NULL),
  ('FR', 'Alixan', NULL),
  ('FR', 'Alleyras', NULL),
  ('FR', 'Altillac', NULL),
  ('FR', 'Amboise', NULL),
  ('FR', 'Ammerschwihr', NULL),
  ('FR', 'Ansouis', NULL),
  ('FR', 'Arcachon', NULL),
  ('FR', 'Arcangues', NULL),
  ('FR', 'Argentan', NULL),
  ('FR', 'Arles', NULL),
  ('FR', 'Arès', NULL),
  ('FR', 'Aumont-Aubrac', NULL),
  ('FR', 'Aureville', NULL),
  ('FR', 'Autrans-Méaudre en Vercors', NULL),
  ('FR', 'Avignon', NULL),
  ('FR', 'Baden', NULL),
  ('FR', 'Baerenthal', NULL),
  ('FR', 'Bagnoles-de-l''Orne', NULL),
  ('FR', 'Bandol', NULL),
  ('FR', 'Barbentane', NULL),
  ('FR', 'Barr', NULL),
  ('FR', 'Beaulieu-sur-Mer', NULL),
  ('FR', 'Beaune', NULL),
  ('FR', 'Belcastel', NULL),
  ('FR', 'Belle-Église', NULL),
  ('FR', 'Biarritz', NULL),
  ('FR', 'Bidart', NULL),
  ('FR', 'Biot', NULL),
  ('FR', 'Blainville-sur-Mer', NULL),
  ('FR', 'Blois', NULL),
  ('FR', 'Boeschepe', NULL),
  ('FR', 'Boismorand', NULL),
  ('FR', 'Bommes', NULL),
  ('FR', 'Bonifacio', NULL),
  ('FR', 'Bonnieux', NULL),
  ('FR', 'Bonnétage', NULL),
  ('FR', 'Bordeaux', NULL),
  ('FR', 'Bouliac', NULL),
  ('FR', 'Boulleret', NULL),
  ('FR', 'Bourg-Charente', NULL),
  ('FR', 'Brantôme', NULL),
  ('FR', 'Brem-sur-Mer', NULL),
  ('FR', 'Brest', NULL),
  ('FR', 'Brive-la-Gaillarde', NULL),
  ('FR', 'Bry', NULL),
  ('FR', 'Brétignolles-sur-Mer', NULL),
  ('FR', 'Busnes', NULL),
  ('FR', 'Béziers', NULL),
  ('FR', 'Cabourg', NULL),
  ('FR', 'Cadenet', NULL),
  ('FR', 'Caen', NULL),
  ('FR', 'Calas-Cabriès', NULL),
  ('FR', 'Calvisson', NULL),
  ('FR', 'Cancale', NULL),
  ('FR', 'Cannes', NULL),
  ('FR', 'Carcassonne', NULL),
  ('FR', 'Carnac', NULL),
  ('FR', 'Carry-le-Rouet', NULL),
  ('FR', 'Cassel', NULL),
  ('FR', 'Cassis', NULL),
  ('FR', 'Cellettes', NULL),
  ('FR', 'Chagny', NULL),
  ('FR', 'Champillon', NULL),
  ('FR', 'Chantilly', NULL),
  ('FR', 'Charmes-sur-Rhône', NULL),
  ('FR', 'Charols', NULL),
  ('FR', 'Chartres', NULL),
  ('FR', 'Chassy', NULL),
  ('FR', 'Chaudes-Aigues', NULL),
  ('FR', 'Cherbourg-en-Cotentin', NULL),
  ('FR', 'Cheverny', NULL),
  ('FR', 'Chonas-l''Amballan', NULL),
  ('FR', 'Châlons-en-Champagne', NULL),
  ('FR', 'Château-Arnoux-Saint-Auban', NULL),
  ('FR', 'Ciboure', NULL),
  ('FR', 'Cognac', NULL),
  ('FR', 'Collioure', NULL),
  ('FR', 'Colmar', NULL),
  ('FR', 'Colombey-les-Deux-Églises', NULL),
  ('FR', 'Colombières-sur-Orb', NULL),
  ('FR', 'Colomiers', NULL),
  ('FR', 'Colroy-la-Roche', NULL),
  ('FR', 'Combrit', NULL),
  ('FR', 'Conques-en-Rouergue', NULL),
  ('FR', 'Corrençon-en-Vercors', NULL),
  ('FR', 'Couilly-Pont-aux-Dames', NULL),
  ('FR', 'Courban', NULL),
  ('FR', 'Courcelles-sur-Vesle', NULL),
  ('FR', 'Courchevel', NULL),
  ('FR', 'Croix', NULL),
  ('FR', 'Cucuron', NULL),
  ('FR', 'Céret', NULL),
  ('FR', 'Danjoutin', NULL),
  ('FR', 'Deauville', NULL),
  ('FR', 'Dieppe', NULL),
  ('FR', 'Dijon', NULL),
  ('FR', 'Dinard', NULL),
  ('FR', 'Dole', NULL),
  ('FR', 'Drusenheim', NULL),
  ('FR', 'Ensisheim', NULL),
  ('FR', 'Espelette', NULL),
  ('FR', 'Eugénie-les-Bains', NULL),
  ('FR', 'Faulquemont', NULL),
  ('FR', 'Flassans-sur-Issole', NULL),
  ('FR', 'Flayosc', NULL),
  ('FR', 'Floressas', NULL),
  ('FR', 'Fondettes', NULL),
  ('FR', 'Fontainebleau', NULL),
  ('FR', 'Fontjoncouse', NULL),
  ('FR', 'Gambais', NULL),
  ('FR', 'Garons', NULL),
  ('FR', 'Gevrey-Chambertin', NULL),
  ('FR', 'Gien', NULL),
  ('FR', 'Gigondas', NULL),
  ('FR', 'Giverny', NULL),
  ('FR', 'Grane', NULL),
  ('FR', 'Granges-les-Beaumont', NULL),
  ('FR', 'Grenoble', NULL),
  ('FR', 'Grignan', NULL),
  ('FR', 'Guéthary', NULL),
  ('FR', 'Gémenos', NULL),
  ('FR', 'Hagondange', NULL),
  ('FR', 'Hasparren', NULL),
  ('FR', 'Illhaeusern', NULL),
  ('FR', 'Issy-les-Moulineaux', NULL),
  ('FR', 'Joigny', NULL),
  ('FR', 'Joucas', NULL),
  ('FR', 'Juan-les-Pins', NULL),
  ('FR', 'Kaysersberg', NULL),
  ('FR', 'Kervignac', NULL),
  ('FR', 'L''Herbaudière', NULL),
  ('FR', 'L''Isle-sur-la-Sorgue', NULL),
  ('FR', 'La Ciotat', NULL),
  ('FR', 'La Colle-sur-Loup', NULL),
  ('FR', 'La Croix-Valmer', NULL),
  ('FR', 'La Ferrière-aux-Étangs', NULL),
  ('FR', 'La Flotte', NULL),
  ('FR', 'La Madelaine-sous-Montreuil', NULL),
  ('FR', 'La Plaine-sur-Mer', NULL),
  ('FR', 'La Roche-sur-Yon', NULL),
  ('FR', 'La Rochelle', NULL),
  ('FR', 'La Vancelle', NULL),
  ('FR', 'La Wantzenau', NULL),
  ('FR', 'Lacave', NULL),
  ('FR', 'Laguiole', NULL),
  ('FR', 'Langres', NULL),
  ('FR', 'Languimberg', NULL),
  ('FR', 'Lastours', NULL),
  ('FR', 'Laubach', NULL),
  ('FR', 'Lavalette', NULL),
  ('FR', 'Le Broc', NULL),
  ('FR', 'Le Cannet', NULL),
  ('FR', 'Le Castellet', NULL),
  ('FR', 'Le Lavandou', NULL),
  ('FR', 'Le Mans', NULL),
  ('FR', 'Le Puy-Sainte-Réparade', NULL),
  ('FR', 'Le Puy-en-Velay', NULL),
  ('FR', 'Les Arcs', NULL),
  ('FR', 'Les Baux-de-Provence', NULL),
  ('FR', 'Les Eyzies-de-Tayac-Sireuil', NULL),
  ('FR', 'Les Sables-d''Olonne', NULL),
  ('FR', 'Les Vans', NULL),
  ('FR', 'Leucate', NULL),
  ('FR', 'Levernois', NULL),
  ('FR', 'Lille', NULL),
  ('FR', 'Loches', NULL),
  ('FR', 'Lorgues', NULL),
  ('FR', 'Lorient', NULL),
  ('FR', 'Lormont', NULL),
  ('FR', 'Lunéville', NULL),
  ('FR', 'Lyons-la-Forêt', NULL),
  ('FR', 'Magescq', NULL),
  ('FR', 'Malataverne', NULL),
  ('FR', 'Malbuisson', NULL),
  ('FR', 'Malling', NULL),
  ('FR', 'Mandelieu-la-Napoule', NULL),
  ('FR', 'Mane', NULL),
  ('FR', 'Manosque', NULL),
  ('FR', 'Mareuil-sur-Lay-Dissais', NULL),
  ('FR', 'Marseille', NULL),
  ('FR', 'Martillac', NULL),
  ('FR', 'Massignac', NULL),
  ('FR', 'Mayenne', NULL),
  ('FR', 'Menton', NULL),
  ('FR', 'Metz', NULL),
  ('FR', 'Meudon', NULL),
  ('FR', 'Moirax', NULL),
  ('FR', 'Monbazillac', NULL),
  ('FR', 'Monestier', NULL),
  ('FR', 'Monswiller', NULL),
  ('FR', 'Mont-de-Marsan', NULL),
  ('FR', 'Montbazon', NULL),
  ('FR', 'Montbron', NULL),
  ('FR', 'Montchenot', NULL),
  ('FR', 'Montenach', NULL),
  ('FR', 'Montlivault', NULL),
  ('FR', 'Montpellier', NULL),
  ('FR', 'Montrabé', NULL),
  ('FR', 'Montreuil', 'Seine-Saint-Denis'),
  ('FR', 'Montréverd', NULL),
  ('FR', 'Moustiers-Sainte-Marie', NULL),
  ('FR', 'Mulhouse', NULL),
  ('FR', 'Méribel', NULL),
  ('FR', 'Nancy', NULL),
  ('FR', 'Narbonne', NULL),
  ('FR', 'Nieul', NULL),
  ('FR', 'Névez', NULL),
  ('FR', 'Nîmes', NULL),
  ('FR', 'Obernai', NULL),
  ('FR', 'Olmeto', NULL),
  ('FR', 'Parnac', NULL),
  ('FR', 'Payrin-Augmontel', NULL),
  ('FR', 'Pernand-Vergelesses', NULL),
  ('FR', 'Perpignan', NULL),
  ('FR', 'Plomodiern', NULL),
  ('FR', 'Plougonvelin', NULL),
  ('FR', 'Plouider', NULL),
  ('FR', 'Pommard', NULL),
  ('FR', 'Pont-Aven', NULL),
  ('FR', 'Port-Louis', NULL),
  ('FR', 'Porticcio', NULL),
  ('FR', 'Porto-Vecchio', NULL),
  ('FR', 'Prenois', NULL),
  ('FR', 'Pujaudran', NULL),
  ('FR', 'Pujaut', NULL),
  ('FR', 'Pupillin', NULL),
  ('FR', 'Puylausic', NULL),
  ('FR', 'Pyla-sur-Mer', NULL),
  ('FR', 'Périgueux', NULL),
  ('FR', 'Pézenas', NULL),
  ('FR', 'Quimper', NULL),
  ('FR', 'Quint-Fonsegrives', NULL),
  ('FR', 'Ramatuelle', NULL),
  ('FR', 'Reims', NULL),
  ('FR', 'Rhinau', NULL),
  ('FR', 'Riquewihr', NULL),
  ('FR', 'Rixheim', NULL),
  ('FR', 'Rodez', NULL),
  ('FR', 'Rolleboise', NULL),
  ('FR', 'Romorantin-Lanthenay', NULL),
  ('FR', 'Roubion', NULL),
  ('FR', 'Rouen', NULL),
  ('FR', 'Rouvres-en-Xaintois', NULL),
  ('FR', 'Rueil-Malmaison', NULL),
  ('FR', 'Sabran', NULL),
  ('FR', 'Saché', NULL),
  ('FR', 'Saint-Alban-de-Roche', NULL),
  ('FR', 'Saint-Bonnet-le-Froid', NULL),
  ('FR', 'Saint-Cannat', NULL),
  ('FR', 'Saint-Cyprien', NULL),
  ('FR', 'Saint-Céré', NULL),
  ('FR', 'Saint-Didier-de-la-Tour', NULL),
  ('FR', 'Saint-Galmier', NULL),
  ('FR', 'Saint-Germain', 'Ardeche'),
  ('FR', 'Saint-Hilaire-d''Ozilhan', NULL),
  ('FR', 'Saint-Hilaire-de-Brethmas', NULL),
  ('FR', 'Saint-Jean-Cap-Ferrat', NULL),
  ('FR', 'Saint-Jean-de-Blaignac', NULL),
  ('FR', 'Saint-Jean-de-Luz', NULL),
  ('FR', 'Saint-Joachim', NULL),
  ('FR', 'Saint-Léon-sur-Vézère', NULL),
  ('FR', 'Saint-Lô', NULL),
  ('FR', 'Saint-Malo', NULL),
  ('FR', 'Saint-Martin-de-Belleville', NULL),
  ('FR', 'Saint-Martin-sur-la-Chambre', NULL),
  ('FR', 'Saint-Médard', 'Lot'),
  ('FR', 'Saint-Méloir-des-Ondes', NULL),
  ('FR', 'Saint-Omer', NULL),
  ('FR', 'Saint-Paul-de-Vence', NULL),
  ('FR', 'Saint-Pée-sur-Nivelle', NULL),
  ('FR', 'Saint-Rémy', 'Saone-et-Loire'),
  ('FR', 'Saint-Rémy-de-Provence', NULL),
  ('FR', 'Saint-Théoffrey', NULL),
  ('FR', 'Saint-Tropez', NULL),
  ('FR', 'Saint-Vincent-de-Tyrosse', NULL),
  ('FR', 'Saint-Émilion', NULL),
  ('FR', 'Salon-de-Provence', NULL),
  ('FR', 'Sampans', NULL),
  ('FR', 'Sancerre', NULL),
  ('FR', 'Sarreguemines', NULL),
  ('FR', 'Sartène', NULL),
  ('FR', 'Saulieu', NULL),
  ('FR', 'Sauternes', NULL),
  ('FR', 'Seignosse', NULL),
  ('FR', 'Sens', NULL),
  ('FR', 'Servon', NULL),
  ('FR', 'Sierentz', NULL),
  ('FR', 'Steige', NULL),
  ('FR', 'Strasbourg', NULL),
  ('FR', 'Théoule-sur-Mer', NULL),
  ('FR', 'Tignes', NULL),
  ('FR', 'Tinqueux', NULL),
  ('FR', 'Toulon', NULL),
  ('FR', 'Toulouse', NULL),
  ('FR', 'Tournemire', NULL),
  ('FR', 'Tournus', NULL),
  ('FR', 'Tourrettes', NULL),
  ('FR', 'Trosly-Loire', NULL),
  ('FR', 'Trémolat', NULL),
  ('FR', 'Uriage-les-Bains', NULL),
  ('FR', 'Uzès', NULL),
  ('FR', 'Val-Thorens', NULL),
  ('FR', 'Val-d''Isère', NULL),
  ('FR', 'Valdeblore', NULL),
  ('FR', 'Valence', NULL),
  ('FR', 'Valmont', NULL),
  ('FR', 'Vannes', NULL),
  ('FR', 'Vault-de-Lugny', NULL),
  ('FR', 'Versailles', NULL),
  ('FR', 'Vienne', NULL),
  ('FR', 'Ville-d''Avray', NULL),
  ('FR', 'Villeneuve-d''Ascq', NULL),
  ('FR', 'Villeneuve-le-Comte', NULL),
  ('FR', 'Villeneuve-lès-Avignon', NULL),
  ('FR', 'Vinay', NULL),
  ('FR', 'Vincennes', NULL),
  ('FR', 'Wihr-au-Val', NULL),
  ('FR', 'Wingen-sur-Moder', NULL),
  ('FR', 'Èze', NULL),
  ('FR', 'Èze-Bord-de-Mer', NULL),
  ('FR', 'Épinal', NULL),
  ('FR', 'Étouy', NULL)
on conflict (country_code, name, coalesce(region, ''))
do nothing;
